In [1]:
from alpha_vantage.timeseries import TimeSeries
import matplotlib.pyplot as plt
from datetime import date
import numpy as np
import pandas as pd

In [2]:
import datetime
import yfinance as yf
from sklearn.preprocessing import StandardScaler

In [3]:
# ts = TimeSeries(key='QG04XBNLP8MZMKF1', output_format='pandas')
# data, meta_data = ts.get_intraday(symbol='RH',interval='1min', outputsize='full')

In [4]:
#data = data.iloc[::-1]

In [5]:
#data.shape

In [6]:
#data

In [7]:
# first_dex = 0
# min_since = []
# running_secs = 0
# for i in range(data.shape[0]):
#     if data.index[first_dex].dayofyear != data.index[i].dayofyear:
#         first_dex = i
#     temp = data.index[i] - data.index[first_dex] 
#     min_since.append(temp.seconds)

In [8]:
#min_since = np.array(min_since)/60

In [9]:
#df = pd.DataFrame(data.index)['date'].apply(lambda x: [x.dayofweek, x.month, x.day, x.hour, x.minute])

In [10]:
#temp = pd.DataFrame(df.to_list(), columns = ['day_of_week', 'month', 'day', 'hour', 'min'])

In [11]:
#dex = np.array(list(temp.index))+1

In [12]:
# temp['data_pt_dex'] = dex
# temp['min_since_open'] = min_since

In [13]:
# temp['open'] = data['1. open'].values
# temp['high'] = data['2. high'].values
# temp['low'] = data['3. low'].values
# temp['close'] = data['4. close'].values
# temp['volume'] = data['5. volume'].values

In [14]:
#temp

In [15]:
#plt.plot(temp['min_since_open'])

In [16]:
msft = yf.Ticker("MSFT")

In [17]:
msft.history(period = '1d', interval = '1m')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2020-10-06 09:30:00-04:00,208.82,209.39,208.72,209.05,837023,0,0
2020-10-06 09:31:00-04:00,209.01,209.31,208.99,209.04,104367,0,0
2020-10-06 09:32:00-04:00,209.03,209.31,209.00,209.16,135682,0,0
2020-10-06 09:33:00-04:00,209.15,209.49,209.13,209.20,120278,0,0
2020-10-06 09:34:00-04:00,209.18,209.33,209.18,209.29,79120,0,0
...,...,...,...,...,...,...,...
2020-10-06 15:55:00-04:00,205.87,206.35,205.85,206.04,218071,0,0
2020-10-06 15:56:00-04:00,206.05,206.11,205.66,206.03,152382,0,0
2020-10-06 15:57:00-04:00,206.00,206.11,205.88,206.06,171563,0,0
2020-10-06 15:58:00-04:00,206.05,206.05,205.80,205.98,167570,0,0
2020-10-06 15:59:00-04:00,205.98,206.31,205.73,205.91,622126,0,0

In [18]:
data = msft.history(period = '10m', interval = '1m')

In [19]:
data

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2020-10-02 15:50:00-04:00,207.24,207.34,206.72,206.75,0,0,0
2020-10-02 15:51:00-04:00,206.76,206.87,206.68,206.74,115172,0,0
2020-10-02 15:52:00-04:00,206.72,206.80,206.62,206.75,126893,0,0
2020-10-02 15:53:00-04:00,206.75,206.87,206.67,206.72,110945,0,0
2020-10-02 15:54:00-04:00,206.73,206.73,206.41,206.41,178148,0,0
2020-10-02 15:55:00-04:00,206.40,206.44,206.16,206.18,198182,0,0
2020-10-02 15:56:00-04:00,206.18,206.32,206.12,206.18,239386,0,0
2020-10-02 15:57:00-04:00,206.18,206.44,206.12,206.44,315095,0,0
2020-10-02 15:58:00-04:00,206.43,206.50,206.27,206.43,277901,0,0
2020-10-02 15:59:00-04:00,206.43,206.53,206.04,206.18,584940,0,0

In [20]:
data.index[0]

Timestamp('2020-10-02 15:50:00-0400', tz='America/New_York')

In [21]:
data.index[1].year

2020

In [22]:
def get_min_since(data):
    '''
    retrieves the min since market open for past data
    
    input(s): dataframe with past minute granularity data
    '''
    first_dex = 0
    min_since = []
    running_secs = 0
    for i in range(data.shape[0]):
        date = pd.Timestamp(data['Datetime'][i])
        temp = date - pd.Timestamp(year=date.year, month=date.month, day = date.day, hour=9, minute=30, second=0, microsecond=0)#,  tz='America/New_York')#data.index[first_dex] 
        min_since.append(temp.seconds)
    min_since = np.array(min_since)/60
    
    return min_since

In [23]:
def process_timestamp(data, min_since):
    '''
    processes timestamp into usable machine learning data
    adds new features to data df
    might need adjustments in the future for better data rather than just ordinal encodings 
    
    input(s): dataframe with minute granularity data, array with min_since data
    output(s): df with new features
    '''
    df = data['Datetime'].apply(lambda x: [pd.Timestamp(x).dayofweek, pd.Timestamp(x).month, pd.Timestamp(x).day, pd.Timestamp(x).hour, pd.Timestamp(x).minute])
    temp = pd.DataFrame(df.to_list(), columns = ['day_of_week', 'month', 'day', 'hour', 'min'])
    dex = np.array(list(temp.index))+1
    
    temp['data_pt_dex'] = dex
    temp['min_since_open'] = min_since
    
    temp['open'] = data['Open'].values
    temp['high'] = data['High'].values
    temp['low'] = data['Low'].values
    temp['close'] = data['Close'].values
    temp['volume'] = data['Volume'].values
    
    return temp

In [24]:
#min_since = get_min_since(data)

In [25]:
#process_timestamp(data, min_since)

In [26]:
msft.options

('2020-10-08',
 '2020-10-15',
 '2020-10-22',
 '2020-10-29',
 '2020-11-05',
 '2020-11-12',
 '2020-11-19',
 '2020-12-17',
 '2021-01-14',
 '2021-02-18',
 '2021-03-18',
 '2021-04-15',
 '2021-06-17',
 '2021-07-15',
 '2021-09-16',
 '2022-01-20',
 '2022-03-17',
 '2022-06-16',
 '2022-09-15',
 '2023-01-19')

In [27]:
msft.option_chain(date='2020-10-15').puts

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,MSFT201016P00080000,2020-10-01 15:38:02,80.0,0.01,0.00,0.01,0.000000,0.000000,5,1452,1.468753,False,REGULAR,USD
1,MSFT201016P00085000,2020-09-15 18:14:44,85.0,0.03,0.00,0.01,0.000000,0.000000,16,922,1.375003,False,REGULAR,USD
2,MSFT201016P00090000,2020-09-24 13:50:27,90.0,0.01,0.00,0.01,0.000000,0.000000,4,1176,1.312503,False,REGULAR,USD
3,MSFT201016P00095000,2020-10-01 17:29:05,95.0,0.01,0.00,0.01,0.000000,0.000000,120,1325,1.218754,False,REGULAR,USD
4,MSFT201016P00100000,2020-09-24 15:10:04,100.0,0.06,0.00,0.11,0.000000,0.000000,2,2028,1.414065,False,REGULAR,USD
5,MSFT201016P00105000,2020-09-24 15:41:49,105.0,0.04,0.00,0.09,0.000000,0.000000,5,693,1.296879,False,REGULAR,USD
6,MSFT201016P00110000,2020-10-01 14:41:35,110.0,0.02,0.00,0.05,0.000000,0.000000,30,895,1.140629,False,REGULAR,USD
7,MSFT201016P00115000,2020-10-02 13:30:02,115.0,0.02,0.01,0.04,0.010000,100.000000,2,717,1.070317,False,REGULAR,USD
8,MSFT201016P00120000,2020-10-02 17:03:26,120.0,0.02,0.01,0.15,-0.010000,-33.333336,1,4225,1.126957,False,REGULAR,USD
9,MSFT201016P00125000,2020-10-01 15:03:33,125.0,0.01,0.00,0.09,0.000000,0.000000,5,1872,0.984375,False,REGULAR,USD
10,MSFT201016P00130000,2020-10-02 16:29:42,130.0,0.03,0.00,0.04,0.010000,50.000000,338,5788,0.835939,False,REGULAR,USD
11,MSFT201016P00135000,2020-10-02 19:10:09,135.0,0.04,0.02,0.05,0.020000,100.000000,20,2062,0.820314,False,REGULAR,USD
12,MSFT201016P00140000,2020-10-02 19:14:06,140.0,0.04,0.01,0.12,-0.010000,-20.000004,11,3011,0.810549,False,REGULAR,USD
13,MSFT201016P00145000,2020-10-02 19:14:06,145.0,0.05,0.00,0.06,-0.010000,-16.666664,41,4230,0.679691,False,REGULAR,USD
14,MSFT201016P00150000,2020-10-02 18:18:00,150.0,0.08,0.04,0.14,0.030000,59.999996,223,10046,0.707034,False,REGULAR,USD
15,MSFT201016P00155000,2020-10-01 18:59:13,155.0,0.07,0.07,0.16,0.000000,0.000000,564,3145,0.664066,False,REGULAR,USD
16,MSFT201016P00160000,2020-10-02 19:56:36,160.0,0.13,0.04,0.18,0.050000,62.500000,155,7148,0.594731,False,REGULAR,USD
17,MSFT201016P00165000,2020-10-02 19:14:28,165.0,0.17,0.13,0.21,0.050000,41.666670,65,4517,0.566411,False,REGULAR,USD
18,MSFT201016P00170000,2020-10-02 19:41:55,170.0,0.17,0.15,0.19,0.040000,30.769238,98,8934,0.500982,False,REGULAR,USD
19,MSFT201016P00175000,2020-10-02 19:55:36,175.0,0.23,0.20,0.23,0.050000,27.777777,378,11648,0.459478,False,REGULAR,USD
20,MSFT201016P00180000,2020-10-02 19:57:32,180.0,0.32,0.30,0.37,0.090000,39.130430,399,8617,0.431158,False,REGULAR,USD
21,MSFT201016P00185000,2020-10-02 19:58:04,185.0,0.52,0.50,0.55,0.210000,67.741930,1191,20879,0.394781,False,REGULAR,USD
22,MSFT201016P00187500,2020-10-02 19:56:49,187.5,0.71,0.65,0.72,0.340000,91.891884,1162,1396,0.383063,False,REGULAR,USD
23,MSFT201016P00190000,2020-10-02 19:59:32,190.0,0.90,0.86,0.93,0.450000,100.000000,1790,13399,0.370123,False,REGULAR,USD
24,MSFT201016P00192500,2020-10-02 19:59:52,192.5,1.23,1.15,1.23,0.600000,95.238100,1394,1905,0.360236,False,REGULAR,USD
25,MSFT201016P00195000,2020-10-02 19:59:54,195.0,1.59,1.41,1.67,0.780000,96.296295,2006,12802,0.355231,False,REGULAR,USD
26,MSFT201016P00197500,2020-10-02 19:59:35,197.5,2.08,2.03,2.20,1.010000,94.392510,811,1290,0.347907,False,REGULAR,USD
27,MSFT201016P00200000,2020-10-02 19:59:32,200.0,2.85,2.72,2.88,1.500000,111.111110,3062,18694,0.341803,False,REGULAR,USD
28,MSFT201016P00202500,2020-10-02 19:59:31,202.5,3.65,3.50,3.75,1.840000,101.657470,564,1445,0.338019,False,REGULAR,USD
29,MSFT201016P00205000,2020-10-02 19:59:24,205.0,4.70,4.60,4.75,2.350000,100.000000,1630,17186,0.331550,False,REGULAR,USD
30,MSFT201016P00207500,2020-10-02 19:59:34,207.5,5.84,5.75,6.05,2.880000,97.297300,659,1406,0.332282,True,REGULAR,USD
31,MSFT201016P00210000,2020-10-02 19:56:09,210.0,7.15,7.20,7.50,3.250000,83.333330,1502,44697,0.331061,True,REGULAR,USD
32,MSFT201016P00212500,2020-10-02 19:49:54,212.5,8.85,8.70,9.15,3.800000,75.247530,242,686,0.331550,True,REGULAR,USD
33,MSFT201016P00215000,2020-10-02 19:55:31,215.0,10.57,10.50,10.95,4.300000,68.580536,383,9100,0.331306,True,REGULAR,USD
34,MSFT201016P00217500,2020-10-02 19:37:22,217.5,12.36,11.70,13.20,4.309999,53.540367,67,140,0.356574,True,REGULAR,USD
35,MSFT201016P00220000,2020-10-02 19:28:42,220.0,14.60,13.70,15.35,5.250000,56.149734,83,3557,0.367926,True,REGULAR,USD
36,MSFT201016P00222500,2020-10-02 19:39:01,222.5,15.60,16.00,17.55,4.610001,41.947230,24,340,0.376959,True,REGULAR,USD
37,MSFT201016P00225000,2020-10-02 19:28:04,225.0,18.28,18.30,19.60,5.230001,40.076630,54,6731,0.360602,True,REGULAR,USD
38,MSFT201016P00227500,2020-10-02 19:38:11,227.5,20.16,21.40,22.25,1.770001,9.624799,2,26,0.411871,True,REGULAR,USD
39,MSFT201016P00230000,2020-10-02 17:47:37,230.0,22.55,23.80,24.65,3.900000,20.911526,77,1269,0.430181,True,REGULAR,USD
40,MSFT201016P00235000,2020-10-02 17:19:19,235.0,28.15,27.95,30.10,4.799999,20.556742,2,414,0.550053,True,REGULAR,USD
41,MSFT201016P00240000,2020-10-02 16:44:41,240.0,32.25,32.85,35.05,4.950001,18.131872,2,355,0.604252,True,REGULAR,USD
42,MSFT201016P00245000,2020-10-02 13:40:18,245.0,35.54,37.85,39.85,2.560001,7.762285,1,48,0.633060,True,REGULAR,USD
43,MSFT201016P00250000,2020-10-01 15:30:45,250.0,37.50,42.85,44.80,0.000000,0.000000,1,914,0.678714,True,REGULAR,USD
44,MSFT201016P00255000,2020-09-16 15:37:23,255.0,49.85,47.90,49.80,0.000000,0.000000,5,6,0.730227,True,REGULAR,USD
45,MSFT201016P00260000,2020-09-28 14:37:51,260.0,51.00,52.95,54.75,0.000000,0.000000,1,12,0.770754,True,REGULAR,USD
46,MSFT201016P00265000,2020-09-24 18:51:15,265.0,61.80,58.00,59.70,0.000000,0.000000,4,9,0.503911,True,REGULAR,USD
47,MSFT201016P00270000,2020-09-30 13:40:27,270.0,62.95,63.00,64.65,0.000000,0.000000,1,2,0.844240,True,REGULAR,USD
48,MSFT201016P00275000,2020-09-24 15:47:04,275.0,70.70,68.00,69.55,0.000000,0.000000,8,13,0.866212,True,REGULAR,USD
49,MSFT201016P00280000,2020-09-17 16:07:57,280.0,78.85,73.05,74.50,0.000000,0.000000,8,10,0.895997,True,REGULAR,USD
50,MSFT201016P00285000,2020-09-23 14:35:31,285.0,80.30,78.10,79.60,0.000000,0.000000,2,2,0.630863,True,REGULAR,USD
51,MSFT201016P00290000,2020-09-09 17:24:57,290.0,82.20,83.10,84.50,5.039993,6.531873,2,0,0.976074,True,REGULAR,USD
52,MSFT201016P00300000,2020-10-02 17:41:51,300.0,93.25,93.10,94.50,0.849998,0.919912,5,45,1.051763,True,REGULAR,USD

In [28]:
#opt.puts

In [29]:
#pd.DataFrame(columns = ['Datetime','Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits'])

In [30]:
def get_min_quote(company):
    '''
    gets the current minute data for a given stock
    
    input(s): string - the ticker label for a compant
    return(s): dataframe with all the data points collected
    '''
    ###make the ticker object
    company = yf.Ticker(company)
    not_done = True
    current_day = pd.DataFrame()
    
    ###open and close
    open_ = datetime.time(hour=7, minute=30, second=0, microsecond=0)
    close_ = datetime.time(hour=14, minute=1, second=0, microsecond=0)
    first_iter = 0
    diff_secs = []
    ###run until the day is over 
    while not_done:
        prev_time = current_time
        current_time = datetime.datetime.now()
        ct =  current_time.time()
        diff_secs.append((current_time.second+(current_time.microsecond/1000000)) - (prev_time.second + (prev_time.microsecond/1000000)))

        if ct >= open_ and ct <= close_:
            ###get stock data
            temp = company.history(period = '4m', interval = '1m')
            temp.reset_index(level=0, inplace=True)
            latest_price = temp.iloc[1]
            current_day = current_day.append(latest_price)
            
            ###wait 60 sec
            if first_iter == 0:
                sleep_time = 60
            else:
                sleep_time = (60 - np.mean(diff_secs))

            first_iter += 1
            time.sleep(sleep_time)

        else:
            not_done = False
    
    
    return current_day

In [31]:
def read_data(ticker):
    '''
    reads data in from csv
    
    input(s): ticker string with the ticker label
    output(s): dataframe with the data
    '''
    return pd.read_csv('~/desktop/investin/data/stored_data/{}.csv'.format(ticker), index_col = 0)

In [103]:
data = read_data('MSFT')

In [104]:
#data['Datetime'].to_timestamp()

In [105]:
data['Datetime']

0       2020-09-15 09:30:00
1       2020-09-15 09:31:00
2       2020-09-15 09:32:00
3       2020-09-15 09:33:00
4       2020-09-15 09:34:00
               ...
5056    2020-10-02 15:55:00
5057    2020-10-02 15:56:00
5058    2020-10-02 15:57:00
5059    2020-10-02 15:58:00
5060    2020-10-02 15:59:00
Name: Datetime, Length: 5061, dtype: object

In [106]:
min_since = get_min_since(data)
data = process_timestamp(data, min_since)

In [107]:
data

,day_of_week,month,day,hour,min,data_pt_dex,min_since_open,open,high,low,close,volume
0,1,9,15,9,30,1,0.0,208.42,208.64,207.90,208.18,1001179
1,1,9,15,9,31,2,1.0,208.23,208.55,207.92,208.26,100899
2,1,9,15,9,32,3,2.0,208.26,208.86,208.18,208.39,148654
3,1,9,15,9,33,4,3.0,208.38,208.85,208.33,208.73,110395
4,1,9,15,9,34,5,4.0,208.78,209.18,208.65,209.18,212768
...,...,...,...,...,...,...,...,...,...,...,...,...
5056,4,10,2,15,55,5057,385.0,206.40,206.44,206.16,206.18,198182
5057,4,10,2,15,56,5058,386.0,206.18,206.32,206.12,206.18,239386
5058,4,10,2,15,57,5059,387.0,206.18,206.44,206.12,206.44,315095
5059,4,10,2,15,58,5060,388.0,206.43,206.50,206.27,206.43,277901
5060,4,10,2,15,59,5061,389.0,206.43,206.53,206.04,206.18,584940

In [108]:
class transforms():
    '''
    class for defining some methods for transforming some data
    '''
    def __init__(self, data):
        self.scaler = StandardScaler()
        
        self.pre_transformed = data.copy()
        
        self.transformed = data
        
    def standardize(self):
        '''
        ['open', 'high', 'low', 'close', 'volume'] standard normal transform
        '''
        temp = self.pre_transformed[['open', 'high', 'low', 'close', 'volume']]
        X = temp.values
        self.scaler.fit(X)
        X_trans = self.scaler.transform(X)
        self.transformed[['open', 'high', 'low', 'close', 'volume']] = X_trans
    
    def encode(self, data, col, max_val):
        '''
        helper function to convert cyclical time date to sin/cos       
        '''
        #data[col + '_cos'] = np.cos(2 * np.pi * data[col]/max_val)
        return np.sin(2 * np.pi * data[col].values/max_val)
        
    def sin_trans(self):
        '''
        perform sin transform, i.e. periodic transform for the time data
        '''
        
        for col in ['day_of_week', 'month', 'day', 'hour', 'min', 'min_since_open']:
            ###if you double the period vals are scaled between 0 and 1, but no two unique values map to same point
            max_val = 2*np.max(self.transformed[col].values)
            self.transformed[col] = self.encode(self.transformed, col, max_val)
            
    def data_pt_scaler(self):
        '''
        scale data_pt_dex by x/max_val
        '''
        temp = self.transformed['data_pt_dex'].values
        max_val = np.max(temp)
        self.transformed['data_pt_dex'] = temp/max_val
        
    def all_transforms(self):
        '''
        perform all transforms
        '''
        self.standardize()
        self.sin_trans()
        self.data_pt_scaler()
    
    
    def suplemental_factors(self, rolling_mean_sizes = [10, 30, 100], secant_mean_sizes = [3, 6, 12]):
        '''
        add some supplemental statistics 
        '''
        ###some rolling means
        secant = lambda x: (x[-1] - x[0])/x.shape[0]
        for size, size_2 in zip(rolling_mean_sizes, secant_mean_sizes):
            self.transformed['close_roll_{}'.format(size)] = self.transformed['close'].rolling(window=size, min_periods = 1).mean()
            self.transformed['close_secant_{}'.format(size_2)] = self.transformed['close'].rolling(window=size_2, min_periods = 1).apply(secant, raw = True)

In [109]:
t = transforms(data)

In [110]:
t.all_transforms()

In [111]:
x = t.transformed

In [117]:
np.mean(x['close'][:10])

0.7537999707901791

In [116]:
t.suplemental_factors()

In [119]:
t.transformed

0.7537999707901791

In [43]:
t.scaler.mean_

array([  205.84039123,   205.96238688,   205.71673385,   205.83998024,
       74350.60225252])

In [45]:
t.scaler.var_

array([1.64163589e+01, 1.62762958e+01, 1.65535233e+01, 1.64038956e+01,
       6.93866092e+10])

In [52]:
(t.pre_transformed['volume'][0] - t.scaler.mean_[-1])/np.sqrt(t.scaler.var_[-1])

3.5185319535555766